clear;
clc;
test=imread('Moon.bmp');
[c,s] = wavedec2(test,2,'coif3');
n = [1,2];
p = [10.12,23.28];
nc = wthcoef2('h',c,s,n,p,'s');  
nc = wthcoef2('v',nc,s,n,p,'s');  
nc = wthcoef2('d',nc,s,n,p,'s');  
x1 = waverec2(nc,s,'coif3');
subplot(1,2,1);
imshow(uint8(x1));
imwrite(uint8(x1),'wave1past.bmp');
xx = wthcoef2('v',nc,s,n,p,'s');  
x2 = waverec2(xx,s,'coif3');
subplot(1,2,2);
imshow(uint8(x2));
imwrite(uint8(x2),'wave2past.bmp');
clear;
